export const SET_BOUNDING_CLIENT_RECT = 'SET_BOUNDING_CLIENT_RECT'
export const SET_WINDOW_HEIGHT = 'SET_WINDOW_HEIGHT'
export const SET_VIEW_HEIGHT = 'SET_VIEW_HEIGHT'
export const SET_TABBAR_HEIGHT = 'SET_TABBAR_HEIGHT'
